name: default
kind: pipeline

steps:
  - name: build-branch
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: boro/rancher-agent
      tag: ${DRONE_TAG}
      build_args:
        - VERSION=${DRONE_TAG}

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
