---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - dapper ci

  publish-image:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: boro/rancher-agent
    context: package/
    tag: ${DRONE_TAG}
    secrets: [dockerhub_username, dockerhub_password]
    build_args:
      - VERSION=${DRONE_TAG}
    when:
      branch: master
